---
- hosts: all
  gather_facts: yes
  tasks:
    # IP address of eth0 interface
    - debug: var=ansible_eth0.ipv4.address
    # IP address of LOOPBACK interface
    - debug: var=ansible_lo.ipv4.address
