---
- hosts: all
  # this is by default YES. So no need mention it anyway
  gather_facts: yes
  tasks:
    # Getting the IP address of enp0s3 interface
    - debug: var=ansible_eth0.ipv4.address
    # Getting the IP address of enp0s8 interface
    - debug: var=ansible_lo.ipv4.address
